emerge-webrsync: Create repo location with portage:portage ownership
gentoo/portage pull request #1390
Opened 2024-10-22 14:17 UTC by duxsco

Bug: https://bugs.gentoo.org/707980

2024-10-22 14:30 UTC, duxsco commented
@thesamesam  The commit message isn't empty:

```
❯ git --no-pager show --no-patch --format=%s
emerge-webrsync: Create repo location with portage:portage ownership

❯ git --no-pager show --no-patch --format=%b
Bug: https://bugs.gentoo.org/707980
Signed-off-by: David Sardari <d@duxsco.de>

❯ git --no-pager show --no-patch --format=%B
emerge-webrsync: Create repo location with portage:portage ownership

Bug: https://bugs.gentoo.org/707980
Signed-off-by: David Sardari <d@duxsco.de>
```

2024-10-22 15:05 UTC, floppym commented
We really should not hard-code "portage:portage" for this. See https://bugs.gentoo.org/941605#c9.

2024-10-22 15:10 UTC, duxsco commented
> We really should not hard-code "portage:portage" for this. See https://bugs.gentoo.org/941605#c9.

Agreed, `PORTAGE_USERNAME` or similar is the way to go.

2024-10-22 15:50 UTC, duxsco commented
@floppym fyi, I implemented your suggestion.

2024-10-22 16:02 UTC, floppym requested changes
There's some code in `sync_local()` that hard codes "portage:portage" as well. Would you mind fixing that up?

2024-10-22 16:02 UTC, floppym commented on bin/emerge-webrsync
> +			chown "${PORTAGE_USERNAME:-portage}":"${PORTAGE_GRPNAME:-portage}" "${repo_location}"
Might be worth dying here too.

2024-10-22 16:15 UTC, duxsco commented on bin/emerge-webrsync
> +		mkdir -p "${repo_location}"
done :)

2024-10-22 16:15 UTC, duxsco commented on bin/emerge-webrsync
> +			chown "${PORTAGE_USERNAME:-portage}":"${PORTAGE_GRPNAME:-portage}" "${repo_location}"
done :)

2024-10-22 16:34 UTC, duxsco commented
fyi, there is also:
https://github.com/gentoo/portage/blob/fad3818445d6a16ec5662710a1d292767869c1cc/misc/emerge-delta-webrsync#L524

2025-01-10 08:41 UTC, Flowdalic commented
Is this still work-in-progress?

2025-01-10 16:14 UTC, duxsco commented
@Flowdalic As long as https://bugs.gentoo.org/941977 isn't taken care of, this PR cannot be merged.

2025-01-10 16:36 UTC, thesamesam commented
Just add a default value for now?

2025-01-10 16:41 UTC, thesamesam commented
Also, portage certainly does default to that - it just may not be exported (can't check easily on mobile).

2025-01-11 13:52 UTC, duxsco commented
fyi, I created a new PR:
https://github.com/gentoo/portage/pull/1414

2025-01-11 22:24 UTC, thesamesam commented
Please rebasd this one now thats in

2025-01-15 11:35 UTC, thesamesam commented
Needs another rebase and to be marked as ready, if it is.

2025-01-15 17:53 UTC, duxsco commented
> Needs another rebase and to be marked as ready, if it is.

OK, I use it for a on my laptop first.

2025-01-21 02:16 UTC, thesamesam commented
I think the change looks good, but please:
1) Split the default fix for user/groups into one commit, and
2) Split the chown fix into another
for a total of 2 commits.

Please ideally squash using `git rebase -i` too.

2025-01-21 20:55 UTC, duxsco commented
@thesamesam done. I haven't tested the code yet, as I'm busy with private stuff. But if you think it's kosher, feel free to merge.

2025-01-21 21:02 UTC, closed without merging

2025-01-21 21:05 UTC, thesamesam commented
Thanks.

2025-01-21 21:05 UTC, thesamesam commented
(I am a bit confused as to how you hadn't tested it yet given the PR was from October and the substance of it was the same, so I hope you just mean the latest variant wasn't yet tested.)

2025-01-21 21:09 UTC, duxsco commented
> (I am a bit confused as to how you hadn't tested it yet given the PR was from October and the substance of it was the same, so I hope you just mean the latest variant wasn't yet tested.)

I have tested it at that time. But, I haven't re-tested it recently.

2025-01-21 21:32 UTC, duxsco commented
@thesamesam  As this change https://github.com/gentoo/portage/pull/1416 isn't in current portage yet, I set just now `PORTAGE_USERNAME="portage"` and `PORTAGE_GRPNAME="portage"` in `make.conf` and did a `emerge-webrsync` with non-existent `/var/db/repos/gentoo`. This resulted in the creation of `/var/db/repos/gentoo` with `portage:portage` ownership. Without the settings in `make.conf`, the repo folder gets create with `root:root` ownership.